# Build all and push to container repository
name: build-and-push
on: [push]

env:
  BACKEND_IMAGE: ghcr.io/${{ github.repository_owner }}/j2ee-hello-world

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set version
        id: version
        run: |
          echo "BRANCH=${{ github.ref }}"
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo VERSION=$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: 🎉 Build and push backend image
        run: |
          docker build ./server/ -t $BACKEND_IMAGE:${{ steps.version.outputs.VERSION }}
          docker push $BACKEND_IMAGE:${{ steps.version.outputs.VERSION }}
